.PHONY: build rebuild up down restart logs status psql test test-unit test-warc test-warc-db test-regress test-all check-docs verify bench bench-bm25 bench-lance bench-warc bench-warc-bm25-modes finalize-benchmark-run finalize-warc-bm25-modes-run make-quality-fixture doctor-quality-labels finalize-quality-labels-run finalize-quality-fixture-build-run report-quality-fixture doctor-quality-baseline stage-quality-provenance quality-finalization-preflight finalize-quality-run public-warc-quality-fixture finalize-public-warc-quality-run eval-quality eval-quality-budget eval-public-warc-quality smoke-public-warc build-pg-version smoke-pg-version pg-version-matrix check-release-artifacts smoke-release-artifacts smoke-release-upgrade release-artifacts release-artifacts-matrix smoke-release-artifacts-matrix smoke-release-upgrade-matrix report-release-artifacts report-release-smoke-matrix finalize-release-run doctor-import-summary finalize-import-run report-run-directory write-run-metadata doctor-run-directory finalize-run-directory clean

.PHONY: compare-benchmark-runs finalize-benchmark-comparison-run doctor-real-corpus-input doctor-quality-attempt-identity preflight-quality-inputs doctor-release-upgrade-inputs report-release-upgrade-smoke-matrix

PG_MAJOR ?= 16
PG_FEATURE = pg$(PG_MAJOR)
PG_IMAGE ?= pgwarc_lance:$(PG_FEATURE)
PG_MATRIX ?= 13 14 15 16 17
PG_MATRIX_CONTAINER ?= pgwarc_lance_$(PG_FEATURE)_smoke
PG_MATRIX_USER ?= pgwarc_lance
PG_MATRIX_PASSWORD ?= pgwarc_lance
PG_MATRIX_DB ?= pgwarc_lance_test
DEV_PERMISSIONS ?= 1
PG_DEV_PERMISSIONS ?= 0
ARTIFACT_SMOKE_IMAGE ?= postgres:$(PG_MAJOR)
ARTIFACT_SMOKE_CONTAINER ?= pgwarc_lance_artifact_install_$(PG_FEATURE)
ARTIFACT_SMOKE_TIMEOUT ?= 90
ARTIFACT_UPGRADE_CONTAINER ?= pgwarc_lance_artifact_upgrade_$(PG_FEATURE)
UPGRADE_OLD_VERSION ?=
UPGRADE_NEW_VERSION ?= $(EXT_VERSION)
UPGRADE_OLD_DIST_DIR ?= $(if $(UPGRADE_OLD_VERSION),dist/pgwarc_lance-$(UPGRADE_OLD_VERSION)-$(PG_FEATURE),)
UPGRADE_NEW_DIST_DIR ?= $(DIST_DIR)
UPGRADE_INPUT_DOCTOR_JSON ?= $(if $(BENCH_OUT_DIR),$(BENCH_OUT_DIR)/release_upgrade_input_doctor.json,)
UPGRADE_INPUT_DOCTOR_MARKDOWN ?= $(if $(BENCH_OUT_DIR),$(BENCH_OUT_DIR)/release_upgrade_input_doctor.md,)
BENCH_ROWS ?= 100,500,1000
BENCH_DIM ?= 384
BENCH_BATCH ?= 500
BM25_WORDS ?= 80
WARC_ROWS ?= 1000
WARC_COMPARE_ROWS ?= 100,500,1000
WARC_WORDS ?= 80
WARC_BM25_MODE ?= function
WARC_COMPARE_EXECUTE ?=
WARC_COMPARE_NO_HASH_VECTORS ?=
BENCH_OUT_DIR ?=
RUN_DIR ?= $(BENCH_OUT_DIR)
BENCH_BM25_JSON ?= $(if $(BENCH_OUT_DIR),$(BENCH_OUT_DIR)/bm25.json,)
BENCH_BM25_MARKDOWN ?= $(if $(BENCH_OUT_DIR),$(BENCH_OUT_DIR)/bm25.md,)
BENCH_LANCE_JSON ?= $(if $(BENCH_OUT_DIR),$(BENCH_OUT_DIR)/lance.json,)
BENCH_LANCE_MARKDOWN ?= $(if $(BENCH_OUT_DIR),$(BENCH_OUT_DIR)/lance.md,)
BENCH_WARC_JSON ?= $(if $(BENCH_OUT_DIR),$(BENCH_OUT_DIR)/warc.json,)
BENCH_WARC_MARKDOWN ?= $(if $(BENCH_OUT_DIR),$(BENCH_OUT_DIR)/warc.md,)
BENCH_WARC_BM25_JSON ?= $(if $(BENCH_OUT_DIR),$(BENCH_OUT_DIR)/warc_bm25_modes.json,)
BENCH_WARC_BM25_MARKDOWN ?= $(if $(BENCH_OUT_DIR),$(BENCH_OUT_DIR)/warc_bm25_modes.md,)
BENCH_RUN_DOCTOR_REQUIRE ?= bm25.json lance.json warc.json
BENCH_RUN_METADATA_COMMAND ?= $(if $(RUN_METADATA_COMMAND),$(RUN_METADATA_COMMAND),BENCH_OUT_DIR=$(RUN_DIR) make finalize-benchmark-run)
WARC_BM25_MODES_RUN_DOCTOR_REQUIRE ?= warc_bm25_modes.json
WARC_BM25_MODES_RUN_METADATA_COMMAND ?= $(if $(RUN_METADATA_COMMAND),$(RUN_METADATA_COMMAND),BENCH_OUT_DIR=$(RUN_DIR) make finalize-warc-bm25-modes-run)
RELEASE_MATRIX_JSON ?= $(if $(BENCH_OUT_DIR),$(BENCH_OUT_DIR)/release_artifacts_matrix.json,)
RELEASE_MATRIX_MARKDOWN ?= $(if $(BENCH_OUT_DIR),$(BENCH_OUT_DIR)/release_artifacts_matrix.md,)
RELEASE_SMOKE_TARGET ?= smoke-release-artifacts
RELEASE_SMOKE_MAKE_PROGRAM ?= make
RELEASE_SMOKE_MAKE_VARS ?=
RELEASE_SMOKE_OUTPUT_LINES ?= 40
RELEASE_SMOKE_JSON ?= $(if $(BENCH_OUT_DIR),$(BENCH_OUT_DIR)/release_smoke_matrix.json,)
RELEASE_SMOKE_MARKDOWN ?= $(if $(BENCH_OUT_DIR),$(BENCH_OUT_DIR)/release_smoke_matrix.md,)
RELEASE_RUN_ARTIFACTS_JSON ?= $(if $(RELEASE_MATRIX_JSON),$(RELEASE_MATRIX_JSON),$(if $(RUN_DIR),$(RUN_DIR)/release_artifacts_matrix.json,))
RELEASE_RUN_ARTIFACTS_MARKDOWN ?= $(if $(RELEASE_MATRIX_MARKDOWN),$(RELEASE_MATRIX_MARKDOWN),$(if $(RUN_DIR),$(RUN_DIR)/release_artifacts_matrix.md,))
RELEASE_RUN_SMOKE_JSON ?= $(if $(RELEASE_SMOKE_JSON),$(RELEASE_SMOKE_JSON),$(if $(RUN_DIR),$(RUN_DIR)/release_smoke_matrix.json,))
RELEASE_RUN_SMOKE_MARKDOWN ?= $(if $(RELEASE_SMOKE_MARKDOWN),$(RELEASE_SMOKE_MARKDOWN),$(if $(RUN_DIR),$(RUN_DIR)/release_smoke_matrix.md,))
RELEASE_RUN_METADATA_COMMAND ?= $(if $(RUN_METADATA_COMMAND),$(RUN_METADATA_COMMAND),RELEASE_SMOKE_TARGET=$(RELEASE_SMOKE_TARGET) $(if $(RELEASE_SMOKE_MAKE_VARS),RELEASE_SMOKE_MAKE_VARS='$(RELEASE_SMOKE_MAKE_VARS)' ,)BENCH_OUT_DIR=$(RUN_DIR) make finalize-release-run)
IMPORT_SUMMARY ?=
IMPORT_DOCTOR_JSON ?= $(if $(BENCH_OUT_DIR),$(BENCH_OUT_DIR)/import_doctor.json,)
IMPORT_DOCTOR_MARKDOWN ?= $(if $(BENCH_OUT_DIR),$(BENCH_OUT_DIR)/import_doctor.md,)
IMPORT_RUN_SUMMARY ?= $(if $(RUN_DIR),$(RUN_DIR)/import.summary.json,$(IMPORT_SUMMARY))
IMPORT_RUN_DOCTOR_JSON ?= $(if $(IMPORT_DOCTOR_JSON),$(IMPORT_DOCTOR_JSON),$(if $(RUN_DIR),$(RUN_DIR)/import_doctor.json,))
IMPORT_RUN_DOCTOR_MARKDOWN ?= $(if $(IMPORT_DOCTOR_MARKDOWN),$(IMPORT_DOCTOR_MARKDOWN),$(if $(RUN_DIR),$(RUN_DIR)/import_doctor.md,))
IMPORT_RUN_DOCTOR_REQUIRE ?= import_doctor.json
IMPORT_RUN_METADATA_COMMAND ?= $(if $(RUN_METADATA_COMMAND),$(RUN_METADATA_COMMAND),IMPORT_SUMMARY=$(IMPORT_SUMMARY) BENCH_OUT_DIR=$(RUN_DIR) make finalize-import-run)
RUN_MANIFEST_JSON ?= $(if $(RUN_DIR),$(RUN_DIR)/run_manifest.json,)
RUN_MANIFEST_MARKDOWN ?= $(if $(RUN_DIR),$(RUN_DIR)/run_manifest.md,)
RUN_METADATA_JSON ?= $(if $(RUN_DIR),$(RUN_DIR)/run_metadata.json,)
RUN_METADATA_MARKDOWN ?= $(if $(RUN_DIR),$(RUN_DIR)/run_metadata.md,)
RUN_METADATA_COMMAND ?=
RUN_METADATA_ENV ?= PG_MAJOR PG_MATRIX BENCH_OUT_DIR RUN_DIR WARC_ROWS WARC_WORDS BENCH_DIM BENCH_BATCH WARC_BM25_MODE WARC_COMPARE_ROWS WARC_COMPARE_EXECUTE WARC_COMPARE_NO_HASH_VECTORS QUALITY_FIXTURE QUALITY_PROVENANCE_JSON QUALITY_RUN_PROVENANCE_JSON QUALITY_MIN_SOURCE_DOCS QUALITY_MAX_SOURCE_SKIPPED_RATIO QUALITY_RECORDS_JSONL QUALITY_EMBEDDING_JSONL QUALITY_QUERIES_JSON QUALITY_FIXTURE_MIN_DOCS QUALITY_FIXTURE_MIN_QUERIES QUALITY_BASELINE_MIN_DOCS QUALITY_BASELINE_MIN_QUERIES QUALITY_BASELINE_MIN_EXPECTED_LABELS QUALITY_BASELINE_MIN_HIT_RATE QUALITY_BASELINE_MIN_MRR QUALITY_BASELINE_REQUIRE_REAL_CORPUS QUALITY_LABELS_JSON QUALITY_LABELS_RECORDS_JSONL QUALITY_LABELS_MIN_QUERIES QUALITY_LABELS_MIN_EXPECTED_LABELS REAL_CORPUS_INPUT_JSON REAL_CORPUS_INPUT_MIN_QUERIES REAL_CORPUS_INPUT_MAX_QUERIES PUBLIC_WARC_URL PUBLIC_WARC_PATH PUBLIC_WARC_SOURCE_SPEC_JSON PUBLIC_WARC_QUERY_SPEC_JSON PUBLIC_WARC_PROVENANCE_JSON PUBLIC_WARC_QUALITY_NAME PUBLIC_WARC_QUERY_NAME PUBLIC_WARC_QUERY PUBLIC_WARC_LABEL_TEXT PUBLIC_WARC_VECTOR_DIM IMPORT_SUMMARY RELEASE_SMOKE_TARGET RELEASE_SMOKE_MAKE_PROGRAM RELEASE_SMOKE_MAKE_VARS
RUN_METADATA_ENV += BENCHMARK_BASELINE_JSON BENCHMARK_CANDIDATE_JSON BENCHMARK_MAX_REGRESSION_RATIO BENCHMARK_COMPARE_JSON BENCHMARK_COMPARE_MARKDOWN
RUN_METADATA_ENV += QUALITY_INPUT_PREFLIGHT_REQUIRED QUALITY_INPUT_PREFLIGHT_CORPUS QUALITY_INPUT_PREFLIGHT_QUERIES_JSON QUALITY_INPUT_PREFLIGHT_QRELS_JSON QUALITY_INPUT_PREFLIGHT_RECORDS_JSONL QUALITY_INPUT_PREFLIGHT_PROVENANCE_JSON QUALITY_INPUT_PREFLIGHT_MANIFEST_JSON
RUN_DOCTOR_PROFILE ?= generic
RUN_DOCTOR_REQUIRE ?=
RUN_DOCTOR_JSON ?= $(if $(RUN_DIR),$(RUN_DIR)/run_doctor.json,)
RUN_DOCTOR_MARKDOWN ?= $(if $(RUN_DIR),$(RUN_DIR)/run_doctor.md,)
QUALITY_JSON ?= $(if $(BENCH_OUT_DIR),$(BENCH_OUT_DIR)/quality.json,)
QUALITY_MARKDOWN ?= $(if $(BENCH_OUT_DIR),$(BENCH_OUT_DIR)/quality.md,)
QUALITY_FIXTURE ?=
QUALITY_RECORDS_JSONL ?=
QUALITY_EMBEDDING_JSONL ?=
QUALITY_QUERIES_JSON ?=
QUALITY_LABELS_JSON ?= $(QUALITY_QUERIES_JSON)
QUALITY_LABELS_RECORDS_JSONL ?= $(QUALITY_RECORDS_JSONL)
QUALITY_LABELS_MIN_QUERIES ?= 1
QUALITY_LABELS_MIN_EXPECTED_LABELS ?= 1
QUALITY_LABELS_DOCTOR_JSON ?= $(if $(BENCH_OUT_DIR),$(BENCH_OUT_DIR)/quality_labels_doctor.json,)
QUALITY_LABELS_DOCTOR_MARKDOWN ?= $(if $(BENCH_OUT_DIR),$(BENCH_OUT_DIR)/quality_labels_doctor.md,)
QUALITY_LABELS_RUN_DOCTOR_REQUIRE ?= quality_labels_doctor.json
QUALITY_LABELS_RUN_METADATA_COMMAND ?= $(if $(RUN_METADATA_COMMAND),$(RUN_METADATA_COMMAND),$(if $(QUALITY_LABELS_JSON),QUALITY_LABELS_JSON=$(QUALITY_LABELS_JSON) ,)$(if $(QUALITY_LABELS_RECORDS_JSONL),QUALITY_LABELS_RECORDS_JSONL=$(QUALITY_LABELS_RECORDS_JSONL) ,)BENCH_OUT_DIR=$(RUN_DIR) make finalize-quality-labels-run)
QUALITY_BUILD_RUN_FIXTURE ?= $(if $(RUN_DIR),$(RUN_DIR)/quality.fixture.json,$(QUALITY_FIXTURE_OUTPUT))
QUALITY_BUILD_RUN_DOCTOR_REQUIRE ?= quality_labels_doctor.json quality.fixture.json quality_fixture_report.json
QUALITY_BUILD_RUN_METADATA_COMMAND ?= $(if $(RUN_METADATA_COMMAND),$(RUN_METADATA_COMMAND),QUALITY_RECORDS_JSONL=$(QUALITY_RECORDS_JSONL) QUALITY_EMBEDDING_JSONL=$(QUALITY_EMBEDDING_JSONL) QUALITY_QUERIES_JSON=$(QUALITY_QUERIES_JSON) BENCH_OUT_DIR=$(RUN_DIR) make finalize-quality-fixture-build-run)
QUALITY_FIXTURE_OUTPUT ?= quality.fixture.json
QUALITY_FIXTURE_NAME ?=
QUALITY_FIXTURE_REPORT_JSON ?= $(if $(BENCH_OUT_DIR),$(BENCH_OUT_DIR)/quality_fixture_report.json,)
QUALITY_FIXTURE_REPORT_MARKDOWN ?= $(if $(BENCH_OUT_DIR),$(BENCH_OUT_DIR)/quality_fixture_report.md,)
QUALITY_FIXTURE_MIN_DOCS ?= 1
QUALITY_FIXTURE_MIN_QUERIES ?= 1
QUALITY_PROVENANCE_JSON ?=
QUALITY_RUN_PROVENANCE_JSON ?= $(if $(RUN_DIR),$(RUN_DIR)/warc_provenance.json,)
QUALITY_REPORT_PROVENANCE_JSON = $(if $(QUALITY_PROVENANCE_JSON),$(QUALITY_RUN_PROVENANCE_JSON),)
QUALITY_RUN_PROVENANCE_REQUIRE ?= $(if $(QUALITY_PROVENANCE_JSON),warc_provenance.json,)
QUALITY_MIN_SOURCE_DOCS ?= 0
QUALITY_MAX_SOURCE_SKIPPED_RATIO ?= 1
QUALITY_RUN_METADATA_COMMAND ?= $(if $(RUN_METADATA_COMMAND),$(RUN_METADATA_COMMAND),$(if $(QUALITY_FIXTURE),QUALITY_FIXTURE=$(QUALITY_FIXTURE) ,)$(if $(QUALITY_PROVENANCE_JSON),QUALITY_PROVENANCE_JSON=$(QUALITY_PROVENANCE_JSON) ,)$(if $(filter-out 0,$(QUALITY_MIN_SOURCE_DOCS)),QUALITY_MIN_SOURCE_DOCS=$(QUALITY_MIN_SOURCE_DOCS) ,)$(if $(filter-out 1,$(QUALITY_MAX_SOURCE_SKIPPED_RATIO)),QUALITY_MAX_SOURCE_SKIPPED_RATIO=$(QUALITY_MAX_SOURCE_SKIPPED_RATIO) ,)BENCH_OUT_DIR=$(RUN_DIR) make finalize-quality-run)
QUALITY_BASELINE_FIXTURE_REPORT_JSON ?= $(if $(QUALITY_FIXTURE_REPORT_JSON),$(QUALITY_FIXTURE_REPORT_JSON),$(if $(RUN_DIR),$(RUN_DIR)/quality_fixture_report.json,))
QUALITY_BASELINE_QUALITY_JSON ?= $(if $(QUALITY_JSON),$(QUALITY_JSON),$(if $(RUN_DIR),$(RUN_DIR)/quality.json,))
QUALITY_BASELINE_DOCTOR_JSON ?= $(if $(RUN_DIR),$(RUN_DIR)/quality_baseline_doctor.json,)
QUALITY_BASELINE_DOCTOR_MARKDOWN ?= $(if $(RUN_DIR),$(RUN_DIR)/quality_baseline_doctor.md,)
QUALITY_BASELINE_MIN_DOCS ?= $(QUALITY_FIXTURE_MIN_DOCS)
QUALITY_BASELINE_MIN_QUERIES ?= $(QUALITY_FIXTURE_MIN_QUERIES)
QUALITY_BASELINE_MIN_EXPECTED_LABELS ?= 1
QUALITY_BASELINE_MIN_HIT_RATE ?= 0
QUALITY_BASELINE_MIN_MRR ?= 0
QUALITY_BASELINE_REQUIRE_REAL_CORPUS ?= 0
QUALITY_BASELINE_REAL_CORPUS_ARG = $(if $(filter 1 true yes,$(QUALITY_BASELINE_REQUIRE_REAL_CORPUS)),--require-real-corpus,)
REAL_CORPUS_INPUT_JSON ?=
REAL_CORPUS_INPUT_MIN_QUERIES ?= 20
REAL_CORPUS_INPUT_MAX_QUERIES ?= 50
REAL_CORPUS_INPUT_DOCTOR_JSON ?= $(if $(BENCH_OUT_DIR),$(BENCH_OUT_DIR)/real_corpus_input_doctor.json,)
REAL_CORPUS_INPUT_DOCTOR_MARKDOWN ?= $(if $(BENCH_OUT_DIR),$(BENCH_OUT_DIR)/real_corpus_input_doctor.md,)
QUALITY_INPUT_PREFLIGHT_CORPUS ?=
QUALITY_INPUT_PREFLIGHT_QUERIES_JSON ?=
QUALITY_INPUT_PREFLIGHT_QRELS_JSON ?=
QUALITY_INPUT_PREFLIGHT_RECORDS_JSONL ?=
QUALITY_INPUT_PREFLIGHT_PROVENANCE_JSON ?=
QUALITY_INPUT_PREFLIGHT_MANIFEST_JSON ?=
QUALITY_INPUT_PREFLIGHT_JSON ?= $(if $(BENCH_OUT_DIR),$(BENCH_OUT_DIR)/quality_input_preflight.json,$(if $(RUN_DIR),$(RUN_DIR)/quality_input_preflight.json,))
QUALITY_INPUT_PREFLIGHT_MARKDOWN ?= $(if $(BENCH_OUT_DIR),$(BENCH_OUT_DIR)/quality_input_preflight.md,$(if $(RUN_DIR),$(RUN_DIR)/quality_input_preflight.md,))
QUALITY_INPUT_PREFLIGHT_REQUIRED ?= 0
QUALITY_INPUT_PREFLIGHT_GATE = $(filter 1 true yes,$(QUALITY_INPUT_PREFLIGHT_REQUIRED) $(QUALITY_BASELINE_REQUIRE_REAL_CORPUS))
QUALITY_ATTEMPT_IDENTITY_JSON ?=
QUALITY_ATTEMPT_IDENTITY_DOCTOR_JSON ?= $(if $(BENCH_OUT_DIR),$(BENCH_OUT_DIR)/quality_attempt_identity_doctor.json,)
QUALITY_ATTEMPT_IDENTITY_DOCTOR_MARKDOWN ?= $(if $(BENCH_OUT_DIR),$(BENCH_OUT_DIR)/quality_attempt_identity_doctor.md,)
PUBLIC_WARC_URL ?= https://raw.githubusercontent.com/webrecorder/pywb/main/sample_archive/warcs/example.warc.gz
PUBLIC_WARC_PATH ?=
PUBLIC_WARC_SOURCE_SPEC_JSON ?=
PUBLIC_WARC_QUERY_SPEC_JSON ?=
PUBLIC_WARC_QUALITY_FIXTURE ?= /tmp/pgwarc_lance_public_warc_quality.fixture.json
PUBLIC_WARC_PROVENANCE_JSON ?= $(if $(RUN_DIR),$(RUN_DIR)/warc_provenance.json,)
PUBLIC_WARC_QUALITY_NAME ?= pywb-public-warc-smoke
PUBLIC_WARC_QUERY_NAME ?= example_domain
PUBLIC_WARC_QUERY ?= Example Domain
PUBLIC_WARC_LABEL_TEXT ?= Example Domain
PUBLIC_WARC_VECTOR_DIM ?= 4
PUBLIC_WARC_QUALITY_RUN_FIXTURE ?= $(if $(RUN_DIR),$(RUN_DIR)/quality.fixture.json,$(PUBLIC_WARC_QUALITY_FIXTURE))
PUBLIC_WARC_QUALITY_RECORDS_JSONL ?= $(if $(RUN_DIR),$(RUN_DIR)/records.jsonl,)
PUBLIC_WARC_QUALITY_EMBEDDING_JSONL ?= $(if $(RUN_DIR),$(RUN_DIR)/vectors.jsonl,)
PUBLIC_WARC_QUALITY_QUERIES_JSON ?= $(if $(RUN_DIR),$(RUN_DIR)/quality_queries.json,)
PUBLIC_WARC_QUALITY_RUN_DOCTOR_REQUIRE ?= $(if $(PUBLIC_WARC_PROVENANCE_JSON),$(notdir $(PUBLIC_WARC_PROVENANCE_JSON)),warc_provenance.json)
PUBLIC_WARC_QUALITY_RUN_METADATA_COMMAND ?= $(if $(RUN_METADATA_COMMAND),$(RUN_METADATA_COMMAND),$(if $(PUBLIC_WARC_PATH),PUBLIC_WARC_PATH=$(PUBLIC_WARC_PATH) ,)$(if $(PUBLIC_WARC_SOURCE_SPEC_JSON),PUBLIC_WARC_SOURCE_SPEC_JSON=$(PUBLIC_WARC_SOURCE_SPEC_JSON) ,)$(if $(PUBLIC_WARC_QUERY_SPEC_JSON),PUBLIC_WARC_QUERY_SPEC_JSON=$(PUBLIC_WARC_QUERY_SPEC_JSON) ,)$(if $(filter-out 0,$(QUALITY_MIN_SOURCE_DOCS)),QUALITY_MIN_SOURCE_DOCS=$(QUALITY_MIN_SOURCE_DOCS) ,)$(if $(filter-out 1,$(QUALITY_MAX_SOURCE_SKIPPED_RATIO)),QUALITY_MAX_SOURCE_SKIPPED_RATIO=$(QUALITY_MAX_SOURCE_SKIPPED_RATIO) ,)BENCH_OUT_DIR=$(RUN_DIR) make finalize-public-warc-quality-run)
BENCH_BM25_OUTPUTS = $(if $(BENCH_BM25_JSON),--json-output $(BENCH_BM25_JSON),) $(if $(BENCH_BM25_MARKDOWN),--markdown-output $(BENCH_BM25_MARKDOWN),)
BENCH_LANCE_OUTPUTS = $(if $(BENCH_LANCE_JSON),--json-output $(BENCH_LANCE_JSON),) $(if $(BENCH_LANCE_MARKDOWN),--markdown-output $(BENCH_LANCE_MARKDOWN),)
BENCH_WARC_OUTPUTS = $(if $(BENCH_WARC_JSON),--json-output $(BENCH_WARC_JSON),) $(if $(BENCH_WARC_MARKDOWN),--markdown-output $(BENCH_WARC_MARKDOWN),)
BENCH_WARC_BM25_OUTPUTS = $(if $(BENCH_WARC_BM25_JSON),--json-output $(BENCH_WARC_BM25_JSON),) $(if $(BENCH_WARC_BM25_MARKDOWN),--markdown-output $(BENCH_WARC_BM25_MARKDOWN),)
BENCHMARK_BASELINE_JSON ?=
BENCHMARK_CANDIDATE_JSON ?=
BENCHMARK_MAX_REGRESSION_RATIO ?=
BENCHMARK_COMPARE_JSON ?= $(if $(BENCH_OUT_DIR),$(BENCH_OUT_DIR)/benchmark_comparison.json,)
BENCHMARK_COMPARE_MARKDOWN ?= $(if $(BENCH_OUT_DIR),$(BENCH_OUT_DIR)/benchmark_comparison.md,)
BENCHMARK_COMPARE_OUTPUTS = $(if $(BENCHMARK_COMPARE_JSON),--json-output $(BENCHMARK_COMPARE_JSON),) $(if $(BENCHMARK_COMPARE_MARKDOWN),--markdown-output $(BENCHMARK_COMPARE_MARKDOWN),)
BENCHMARK_COMPARE_RUN_DOCTOR_REQUIRE ?= benchmark_comparison.json
BENCHMARK_COMPARE_RUN_METADATA_COMMAND ?= $(if $(RUN_METADATA_COMMAND),$(RUN_METADATA_COMMAND),BENCHMARK_BASELINE_JSON=$(BENCHMARK_BASELINE_JSON) BENCHMARK_CANDIDATE_JSON=$(BENCHMARK_CANDIDATE_JSON) BENCHMARK_MAX_REGRESSION_RATIO=$(BENCHMARK_MAX_REGRESSION_RATIO) BENCH_OUT_DIR=$(RUN_DIR) make finalize-benchmark-comparison-run)
RELEASE_MATRIX_OUTPUTS = $(if $(RELEASE_MATRIX_JSON),--json-output $(RELEASE_MATRIX_JSON),) $(if $(RELEASE_MATRIX_MARKDOWN),--markdown-output $(RELEASE_MATRIX_MARKDOWN),)
RELEASE_SMOKE_OUTPUTS = $(if $(RELEASE_SMOKE_JSON),--json-output $(RELEASE_SMOKE_JSON),) $(if $(RELEASE_SMOKE_MARKDOWN),--markdown-output $(RELEASE_SMOKE_MARKDOWN),)
RELEASE_SMOKE_MAKE_VAR_ARGS = $(foreach var,$(RELEASE_SMOKE_MAKE_VARS),--make-var "$(var)")
IMPORT_DOCTOR_OUTPUTS = $(if $(IMPORT_DOCTOR_JSON),--json-output $(IMPORT_DOCTOR_JSON),) $(if $(IMPORT_DOCTOR_MARKDOWN),--markdown-output $(IMPORT_DOCTOR_MARKDOWN),)
RUN_MANIFEST_OUTPUTS = $(if $(RUN_MANIFEST_JSON),--json-output $(RUN_MANIFEST_JSON),) $(if $(RUN_MANIFEST_MARKDOWN),--markdown-output $(RUN_MANIFEST_MARKDOWN),)
RUN_METADATA_OUTPUTS = $(if $(RUN_METADATA_JSON),--json-output $(RUN_METADATA_JSON),) $(if $(RUN_METADATA_MARKDOWN),--markdown-output $(RUN_METADATA_MARKDOWN),)
RUN_METADATA_COMMAND_ARG = $(if $(RUN_METADATA_COMMAND),--command "$(RUN_METADATA_COMMAND)",)
RUN_METADATA_ENV_ARGS = $(foreach name,$(RUN_METADATA_ENV),--env $(name))
RUN_DOCTOR_OUTPUTS = $(if $(RUN_DOCTOR_JSON),--json-output $(RUN_DOCTOR_JSON),) $(if $(RUN_DOCTOR_MARKDOWN),--markdown-output $(RUN_DOCTOR_MARKDOWN),)
RUN_DOCTOR_REQUIRE_ARGS = $(foreach path,$(RUN_DOCTOR_REQUIRE),--require $(path))
WARC_COMPARE_EXECUTE_ARG = $(if $(WARC_COMPARE_EXECUTE),--execute,)
WARC_COMPARE_NO_HASH_VECTORS_ARG = $(if $(WARC_COMPARE_NO_HASH_VECTORS),--no-hash-vectors,)
QUALITY_INPUT_PREFLIGHT_CORPUS_ARGS = $(foreach path,$(QUALITY_INPUT_PREFLIGHT_CORPUS),--corpus-path "$(path)")
QUALITY_INPUT_PREFLIGHT_OPTIONAL_ARGS = $(if $(QUALITY_INPUT_PREFLIGHT_RECORDS_JSONL),--records-jsonl "$(QUALITY_INPUT_PREFLIGHT_RECORDS_JSONL)",) $(if $(QUALITY_INPUT_PREFLIGHT_PROVENANCE_JSON),--provenance-json "$(QUALITY_INPUT_PREFLIGHT_PROVENANCE_JSON)",) $(if $(QUALITY_INPUT_PREFLIGHT_MANIFEST_JSON),--manifest-json "$(QUALITY_INPUT_PREFLIGHT_MANIFEST_JSON)",) $(if $(QUALITY_INPUT_PREFLIGHT_JSON),--json-output "$(QUALITY_INPUT_PREFLIGHT_JSON)",) $(if $(QUALITY_INPUT_PREFLIGHT_MARKDOWN),--markdown-output "$(QUALITY_INPUT_PREFLIGHT_MARKDOWN)",)
QUALITY_OUTPUTS = $(if $(QUALITY_JSON),--json-output $(QUALITY_JSON),) $(if $(QUALITY_MARKDOWN),--markdown-output $(QUALITY_MARKDOWN),)
QUALITY_LABELS_RECORDS_ARG = $(if $(QUALITY_LABELS_RECORDS_JSONL),--records-jsonl "$(QUALITY_LABELS_RECORDS_JSONL)",)
QUALITY_LABELS_DOCTOR_OUTPUTS = $(if $(QUALITY_LABELS_DOCTOR_JSON),--json-output $(QUALITY_LABELS_DOCTOR_JSON),) $(if $(QUALITY_LABELS_DOCTOR_MARKDOWN),--markdown-output $(QUALITY_LABELS_DOCTOR_MARKDOWN),)
QUALITY_FIXTURE_REPORT_OUTPUTS = $(if $(QUALITY_FIXTURE_REPORT_JSON),--json-output $(QUALITY_FIXTURE_REPORT_JSON),) $(if $(QUALITY_FIXTURE_REPORT_MARKDOWN),--markdown-output $(QUALITY_FIXTURE_REPORT_MARKDOWN),)
QUALITY_FIXTURE_REPORT_PROVENANCE_ARGS = $(if $(QUALITY_PROVENANCE_JSON),--provenance-json "$(QUALITY_PROVENANCE_JSON)",) --min-source-docs "$(QUALITY_MIN_SOURCE_DOCS)" --max-source-skipped-ratio "$(QUALITY_MAX_SOURCE_SKIPPED_RATIO)"
QUALITY_BASELINE_DOCTOR_OUTPUTS = $(if $(QUALITY_BASELINE_DOCTOR_JSON),--json-output $(QUALITY_BASELINE_DOCTOR_JSON),) $(if $(QUALITY_BASELINE_DOCTOR_MARKDOWN),--markdown-output $(QUALITY_BASELINE_DOCTOR_MARKDOWN),)
REAL_CORPUS_INPUT_DOCTOR_OUTPUTS = $(if $(REAL_CORPUS_INPUT_DOCTOR_JSON),--json-output $(REAL_CORPUS_INPUT_DOCTOR_JSON),) $(if $(REAL_CORPUS_INPUT_DOCTOR_MARKDOWN),--markdown-output $(REAL_CORPUS_INPUT_DOCTOR_MARKDOWN),)
QUALITY_ATTEMPT_IDENTITY_OUTPUTS = $(if $(QUALITY_ATTEMPT_IDENTITY_DOCTOR_JSON),--json-output $(QUALITY_ATTEMPT_IDENTITY_DOCTOR_JSON),) $(if $(QUALITY_ATTEMPT_IDENTITY_DOCTOR_MARKDOWN),--markdown-output $(QUALITY_ATTEMPT_IDENTITY_DOCTOR_MARKDOWN),)
UPGRADE_INPUT_DOCTOR_OUTPUTS = $(if $(UPGRADE_INPUT_DOCTOR_JSON),--json-output $(UPGRADE_INPUT_DOCTOR_JSON),) $(if $(UPGRADE_INPUT_DOCTOR_MARKDOWN),--markdown-output $(UPGRADE_INPUT_DOCTOR_MARKDOWN),)
UPGRADE_INPUT_OLD_VERSION_ARG = $(if $(UPGRADE_OLD_VERSION),--old-version "$(UPGRADE_OLD_VERSION)",)
UPGRADE_INPUT_OLD_DIST_DIR_ARG = $(if $(UPGRADE_OLD_DIST_DIR),--old-dist-dir "$(UPGRADE_OLD_DIST_DIR)",)
UPGRADE_INPUT_NEW_DIST_DIR_ARG = $(if $(UPGRADE_NEW_DIST_DIR),--new-dist-dir "$(UPGRADE_NEW_DIST_DIR)",)
QUALITY_RUN_JSON = $(if $(QUALITY_JSON),$(QUALITY_JSON),$(if $(RUN_DIR),$(RUN_DIR)/quality.json,))
QUALITY_RUN_MARKDOWN = $(if $(QUALITY_MARKDOWN),$(QUALITY_MARKDOWN),$(if $(RUN_DIR),$(RUN_DIR)/quality.md,))
QUALITY_RUN_FIXTURE_REPORT_JSON = $(if $(QUALITY_FIXTURE_REPORT_JSON),$(QUALITY_FIXTURE_REPORT_JSON),$(if $(RUN_DIR),$(RUN_DIR)/quality_fixture_report.json,))
QUALITY_RUN_FIXTURE_REPORT_MARKDOWN = $(if $(QUALITY_FIXTURE_REPORT_MARKDOWN),$(QUALITY_FIXTURE_REPORT_MARKDOWN),$(if $(RUN_DIR),$(RUN_DIR)/quality_fixture_report.md,))
QUALITY_RUN_DOCTOR_REQUIRE ?= quality_baseline_doctor.json
ANALYSIS_MAX_ITERATIONS ?=
ANALYSIS_MAX_QUERIES ?=
ANALYSIS_DEADLINE_SECONDS ?=
ANALYSIS_BUDGET_STATUS_JSON ?= $(if $(BENCH_OUT_DIR),$(BENCH_OUT_DIR)/analysis_budget_status.json,)
ANALYSIS_BUDGET_STATUS_ARG = $(if $(ANALYSIS_BUDGET_STATUS_JSON),--budget-status-json "$(ANALYSIS_BUDGET_STATUS_JSON)",)
QUALITY_QUERY_TIMEOUT_SECONDS ?=
QUALITY_QUERY_TIMEOUT_ARG = $(if $(QUALITY_QUERY_TIMEOUT_SECONDS),--query-timeout-seconds "$(QUALITY_QUERY_TIMEOUT_SECONDS)",)
QUERY_STATEMENT_TIMEOUT_SECONDS ?=
QUERY_STATEMENT_TIMEOUT_ARG = $(if $(QUERY_STATEMENT_TIMEOUT_SECONDS),--query-statement-timeout-seconds "$(QUERY_STATEMENT_TIMEOUT_SECONDS)",)
QUALITY_FIXTURE_ARG = $(if $(QUALITY_FIXTURE),--fixture-json $(QUALITY_FIXTURE),)
QUALITY_FIXTURE_NAME_ARG = $(if $(QUALITY_FIXTURE_NAME),--name $(QUALITY_FIXTURE_NAME),)
PUBLIC_WARC_PATH_ARG = $(if $(PUBLIC_WARC_PATH),--warc-path "$(PUBLIC_WARC_PATH)",)
PUBLIC_WARC_SOURCE_SPEC_ARG = $(if $(PUBLIC_WARC_SOURCE_SPEC_JSON),--source-spec-json "$(PUBLIC_WARC_SOURCE_SPEC_JSON)",)
PUBLIC_WARC_QUERY_SPEC_ARG = $(if $(PUBLIC_WARC_QUERY_SPEC_JSON),--query-spec-json "$(PUBLIC_WARC_QUERY_SPEC_JSON)",)
PUBLIC_WARC_PROVENANCE_ARG = $(if $(PUBLIC_WARC_PROVENANCE_JSON),--manifest-json "$(PUBLIC_WARC_PROVENANCE_JSON)",)
PUBLIC_WARC_QUALITY_ARTIFACT_OUTPUTS = $(if $(PUBLIC_WARC_QUALITY_RECORDS_JSONL),--records-jsonl "$(PUBLIC_WARC_QUALITY_RECORDS_JSONL)",) $(if $(PUBLIC_WARC_QUALITY_EMBEDDING_JSONL),--embedding-jsonl "$(PUBLIC_WARC_QUALITY_EMBEDDING_JSONL)",) $(if $(PUBLIC_WARC_QUALITY_QUERIES_JSON),--queries-json "$(PUBLIC_WARC_QUALITY_QUERIES_JSON)",)
EXT_VERSION ?= $(shell awk -F'"' '/^version =/ {print $$2; exit}' Cargo.toml)
DIST_DIR ?= dist/pgwarc_lance-$(EXT_VERSION)-$(PG_FEATURE)
ARTIFACT_CONTAINER ?= pgwarc_lance_artifacts_$(PG_FEATURE)

build:
	PG_MAJOR=$(PG_MAJOR) DEV_PERMISSIONS=$(DEV_PERMISSIONS) docker compose build

rebuild:
	PG_MAJOR=$(PG_MAJOR) DEV_PERMISSIONS=$(DEV_PERMISSIONS) docker compose build --no-cache

up:
	docker compose up -d
	@echo "waiting for postgres to be healthy..."
	@timeout 60 bash -c 'until docker compose ps postgres | grep -q healthy; do sleep 2; done' || true
	@docker compose ps

down:
	docker compose down

restart:
	docker compose restart

logs:
	docker compose logs -f postgres

status:
	docker compose ps

psql:
	docker compose exec postgres psql -U pgwarc_lance -d pgwarc_lance_test

# smoke test: run tests/test.sql against the live container
test:
	docker compose exec -T postgres psql -U pgwarc_lance -d pgwarc_lance_test -v ON_ERROR_STOP=1 -c 'DROP EXTENSION IF EXISTS pgwarc_lance CASCADE; CREATE EXTENSION pgwarc_lance;'
	docker compose exec -T postgres psql -U pgwarc_lance -d pgwarc_lance_test -v ON_ERROR_STOP=1 < tests/test.sql

# unit test harness: compile the tokenizer module without linking the extension stack
test-unit:
	docker compose exec -T --user postgres postgres bash -lc 'export USER=postgres RUSTUP_HOME=/root/.rustup CARGO_HOME=/root/.cargo PATH="/root/.cargo/bin:$$PATH" && rustc --test /build/tests/unit_tokenizer.rs -o /tmp/pgwarc_lance_unit_tokenizer && /tmp/pgwarc_lance_unit_tokenizer'

test-warc:
	python3 -m unittest discover -s tests -p 'test_*.py'

test-warc-db:
	python3 tests/db_warc_importer.py

# regression test harness: pg_regress SQL tests in tests/pg_regress
test-regress:
	docker compose exec -T --user postgres postgres bash -lc 'set -euo pipefail; export USER=postgres RUSTUP_HOME=/root/.rustup CARGO_HOME=/root/.cargo PATH="/root/.cargo/bin:$$PATH"; cargo pgrx install --pg-config /usr/bin/pg_config; cargo pgrx stop pg16 || true; cargo pgrx start pg16; until pg_isready -h localhost -p 28816 >/dev/null; do sleep 1; done; dropdb -h localhost -p 28816 --if-exists pgwarc_lance_regress; createdb -h localhost -p 28816 pgwarc_lance_regress; rm -rf /tmp/pgwarc_lance_pg_regress; mkdir -p /tmp/pgwarc_lance_pg_regress; tests=$$(find /build/tests/pg_regress/sql -maxdepth 1 -type f -name "*.sql" ! -name "setup.sql" -printf "%f\n" | sed "s/\.sql$$//" | sort | tr "\n" " "); cd /build/tests/pg_regress && /usr/lib/postgresql/16/lib/pgxs/src/test/regress/pg_regress --host localhost --port 28816 --use-existing --dbname=pgwarc_lance_regress --inputdir=/build/tests/pg_regress --outputdir=/tmp/pgwarc_lance_pg_regress setup $$tests'

# all harnesses
test-all: test-unit test-uri-policy test-warc test-regress test test-warc-db test-runtime-safety test-backup-restore test-ingest-replay test-write-cancellation test-search-memory test-bm25-snapshot

check-docs:
	python3 tools/check_docs.py

verify: test-all eval-quality check-docs
	python3 -m py_compile tools/*.py tests/*.py
	git diff --check

bench: bench-bm25 bench-lance bench-warc

finalize-benchmark-run:
	test -n "$(RUN_DIR)"
	mkdir -p "$(RUN_DIR)"
	$(MAKE) bench BENCH_OUT_DIR="$(RUN_DIR)"
	$(MAKE) finalize-run-directory RUN_DIR="$(RUN_DIR)" RUN_METADATA_COMMAND="$(BENCH_RUN_METADATA_COMMAND)" RUN_METADATA_ENV="$(RUN_METADATA_ENV)" RUN_METADATA_JSON="$(RUN_METADATA_JSON)" RUN_METADATA_MARKDOWN="$(RUN_METADATA_MARKDOWN)" RUN_DOCTOR_PROFILE=benchmark RUN_DOCTOR_REQUIRE="$(strip $(BENCH_RUN_DOCTOR_REQUIRE) $(RUN_DOCTOR_REQUIRE))" RUN_DOCTOR_JSON="$(RUN_DOCTOR_JSON)" RUN_DOCTOR_MARKDOWN="$(RUN_DOCTOR_MARKDOWN)" RUN_MANIFEST_JSON="$(RUN_MANIFEST_JSON)" RUN_MANIFEST_MARKDOWN="$(RUN_MANIFEST_MARKDOWN)"

finalize-warc-bm25-modes-run:
	test -n "$(RUN_DIR)"
	mkdir -p "$(RUN_DIR)"
	$(MAKE) bench-warc-bm25-modes BENCH_OUT_DIR="$(RUN_DIR)"
	$(MAKE) finalize-run-directory RUN_DIR="$(RUN_DIR)" RUN_METADATA_COMMAND="$(WARC_BM25_MODES_RUN_METADATA_COMMAND)" RUN_METADATA_ENV="$(RUN_METADATA_ENV)" RUN_METADATA_JSON="$(RUN_METADATA_JSON)" RUN_METADATA_MARKDOWN="$(RUN_METADATA_MARKDOWN)" RUN_DOCTOR_PROFILE=benchmark RUN_DOCTOR_REQUIRE="$(strip $(WARC_BM25_MODES_RUN_DOCTOR_REQUIRE) $(RUN_DOCTOR_REQUIRE))" RUN_DOCTOR_JSON="$(RUN_DOCTOR_JSON)" RUN_DOCTOR_MARKDOWN="$(RUN_DOCTOR_MARKDOWN)" RUN_MANIFEST_JSON="$(RUN_MANIFEST_JSON)" RUN_MANIFEST_MARKDOWN="$(RUN_MANIFEST_MARKDOWN)"

bench-bm25:
	python3 tools/bench_bm25.py --rows $(BENCH_ROWS) --body-words $(BM25_WORDS) $(BENCH_BM25_OUTPUTS)

bench-lance:
	python3 tools/bench_lance.py --rows $(BENCH_ROWS) --dim $(BENCH_DIM) --batch-size $(BENCH_BATCH) $(BENCH_LANCE_OUTPUTS)

bench-warc:
	python3 tools/bench_warc.py --rows $(WARC_ROWS) --body-words $(WARC_WORDS) --vector-dim $(BENCH_DIM) --batch-size $(BENCH_BATCH) --bm25-mode $(WARC_BM25_MODE) $(BENCH_WARC_OUTPUTS)

bench-warc-bm25-modes:
	python3 tools/bench_warc_bm25_modes.py --rows $(WARC_COMPARE_ROWS) --body-words $(WARC_WORDS) --vector-dim $(BENCH_DIM) --batch-size $(BENCH_BATCH) $(WARC_COMPARE_EXECUTE_ARG) $(WARC_COMPARE_NO_HASH_VECTORS_ARG) $(BENCH_WARC_BM25_OUTPUTS)

finalize-benchmark-comparison-run:
	test -n "$(RUN_DIR)"
	test -n "$(BENCHMARK_BASELINE_JSON)"
	test -n "$(BENCHMARK_CANDIDATE_JSON)"
	test -n "$(BENCHMARK_MAX_REGRESSION_RATIO)"
	mkdir -p "$(RUN_DIR)"
	$(MAKE) compare-benchmark-runs BENCHMARK_BASELINE_JSON="$(BENCHMARK_BASELINE_JSON)" BENCHMARK_CANDIDATE_JSON="$(BENCHMARK_CANDIDATE_JSON)" BENCHMARK_MAX_REGRESSION_RATIO="$(BENCHMARK_MAX_REGRESSION_RATIO)" BENCHMARK_COMPARE_JSON="$(RUN_DIR)/benchmark_comparison.json" BENCHMARK_COMPARE_MARKDOWN="$(RUN_DIR)/benchmark_comparison.md"
	$(MAKE) finalize-run-directory RUN_DIR="$(RUN_DIR)" RUN_METADATA_COMMAND="$(BENCHMARK_COMPARE_RUN_METADATA_COMMAND)" RUN_METADATA_ENV="$(RUN_METADATA_ENV)" RUN_METADATA_JSON="$(RUN_METADATA_JSON)" RUN_METADATA_MARKDOWN="$(RUN_METADATA_MARKDOWN)" RUN_DOCTOR_PROFILE=benchmark RUN_DOCTOR_REQUIRE="$(strip $(BENCHMARK_COMPARE_RUN_DOCTOR_REQUIRE) $(RUN_DOCTOR_REQUIRE))" RUN_DOCTOR_JSON="$(RUN_DOCTOR_JSON)" RUN_DOCTOR_MARKDOWN="$(RUN_DOCTOR_MARKDOWN)" RUN_MANIFEST_JSON="$(RUN_MANIFEST_JSON)" RUN_MANIFEST_MARKDOWN="$(RUN_MANIFEST_MARKDOWN)"

compare-benchmark-runs:
	test -n "$(BENCHMARK_BASELINE_JSON)"
	test -n "$(BENCHMARK_CANDIDATE_JSON)"
	test -n "$(BENCHMARK_MAX_REGRESSION_RATIO)"
	python3 tools/compare_benchmark_runs.py --baseline-json "$(BENCHMARK_BASELINE_JSON)" --candidate-json "$(BENCHMARK_CANDIDATE_JSON)" --max-regression-ratio "$(BENCHMARK_MAX_REGRESSION_RATIO)" $(BENCHMARK_COMPARE_OUTPUTS)

doctor-quality-labels:
	test -n "$(QUALITY_LABELS_JSON)"
	python3 tools/doctor_quality_labels.py --queries-json "$(QUALITY_LABELS_JSON)" $(QUALITY_LABELS_RECORDS_ARG) --min-queries "$(QUALITY_LABELS_MIN_QUERIES)" --min-expected-labels "$(QUALITY_LABELS_MIN_EXPECTED_LABELS)" $(QUALITY_LABELS_DOCTOR_OUTPUTS)

finalize-quality-labels-run:
	test -n "$(RUN_DIR)"
	test -n "$(QUALITY_LABELS_JSON)"
	mkdir -p "$(RUN_DIR)"
	$(MAKE) doctor-quality-labels BENCH_OUT_DIR="$(RUN_DIR)" QUALITY_LABELS_JSON="$(QUALITY_LABELS_JSON)" QUALITY_LABELS_RECORDS_JSONL="$(QUALITY_LABELS_RECORDS_JSONL)" QUALITY_LABELS_MIN_QUERIES="$(QUALITY_LABELS_MIN_QUERIES)" QUALITY_LABELS_MIN_EXPECTED_LABELS="$(QUALITY_LABELS_MIN_EXPECTED_LABELS)"
	$(MAKE) finalize-run-directory RUN_DIR="$(RUN_DIR)" RUN_METADATA_COMMAND="$(QUALITY_LABELS_RUN_METADATA_COMMAND)" RUN_METADATA_ENV="$(RUN_METADATA_ENV)" RUN_METADATA_JSON="$(RUN_METADATA_JSON)" RUN_METADATA_MARKDOWN="$(RUN_METADATA_MARKDOWN)" RUN_DOCTOR_PROFILE=generic RUN_DOCTOR_REQUIRE="$(strip $(QUALITY_LABELS_RUN_DOCTOR_REQUIRE) $(RUN_DOCTOR_REQUIRE))" RUN_DOCTOR_JSON="$(RUN_DOCTOR_JSON)" RUN_DOCTOR_MARKDOWN="$(RUN_DOCTOR_MARKDOWN)" RUN_MANIFEST_JSON="$(RUN_MANIFEST_JSON)" RUN_MANIFEST_MARKDOWN="$(RUN_MANIFEST_MARKDOWN)"

finalize-quality-fixture-build-run:
	test -n "$(RUN_DIR)"
	test -n "$(QUALITY_RECORDS_JSONL)"
	test -n "$(QUALITY_EMBEDDING_JSONL)"
	test -n "$(QUALITY_QUERIES_JSON)"
	mkdir -p "$(RUN_DIR)"
	$(MAKE) doctor-quality-labels BENCH_OUT_DIR="$(RUN_DIR)" QUALITY_LABELS_JSON="$(QUALITY_QUERIES_JSON)" QUALITY_LABELS_RECORDS_JSONL="$(QUALITY_RECORDS_JSONL)" QUALITY_LABELS_MIN_QUERIES="$(QUALITY_LABELS_MIN_QUERIES)" QUALITY_LABELS_MIN_EXPECTED_LABELS="$(QUALITY_LABELS_MIN_EXPECTED_LABELS)"
	$(MAKE) make-quality-fixture QUALITY_RECORDS_JSONL="$(QUALITY_RECORDS_JSONL)" QUALITY_EMBEDDING_JSONL="$(QUALITY_EMBEDDING_JSONL)" QUALITY_QUERIES_JSON="$(QUALITY_QUERIES_JSON)" QUALITY_FIXTURE_NAME="$(QUALITY_FIXTURE_NAME)" QUALITY_FIXTURE_OUTPUT="$(QUALITY_BUILD_RUN_FIXTURE)"
	$(MAKE) report-quality-fixture QUALITY_FIXTURE="$(QUALITY_BUILD_RUN_FIXTURE)" QUALITY_PROVENANCE_JSON="$(QUALITY_PROVENANCE_JSON)" QUALITY_MIN_SOURCE_DOCS="$(QUALITY_MIN_SOURCE_DOCS)" QUALITY_MAX_SOURCE_SKIPPED_RATIO="$(QUALITY_MAX_SOURCE_SKIPPED_RATIO)" QUALITY_FIXTURE_MIN_DOCS="$(QUALITY_FIXTURE_MIN_DOCS)" QUALITY_FIXTURE_MIN_QUERIES="$(QUALITY_FIXTURE_MIN_QUERIES)" QUALITY_FIXTURE_REPORT_JSON="$(RUN_DIR)/quality_fixture_report.json" QUALITY_FIXTURE_REPORT_MARKDOWN="$(RUN_DIR)/quality_fixture_report.md"
	$(MAKE) finalize-run-directory RUN_DIR="$(RUN_DIR)" RUN_METADATA_COMMAND="$(QUALITY_BUILD_RUN_METADATA_COMMAND)" RUN_METADATA_ENV="$(RUN_METADATA_ENV)" RUN_METADATA_JSON="$(RUN_METADATA_JSON)" RUN_METADATA_MARKDOWN="$(RUN_METADATA_MARKDOWN)" RUN_DOCTOR_PROFILE=generic RUN_DOCTOR_REQUIRE="$(strip $(QUALITY_BUILD_RUN_DOCTOR_REQUIRE) $(RUN_DOCTOR_REQUIRE))" RUN_DOCTOR_JSON="$(RUN_DOCTOR_JSON)" RUN_DOCTOR_MARKDOWN="$(RUN_DOCTOR_MARKDOWN)" RUN_MANIFEST_JSON="$(RUN_MANIFEST_JSON)" RUN_MANIFEST_MARKDOWN="$(RUN_MANIFEST_MARKDOWN)"

make-quality-fixture:
	test -n "$(QUALITY_RECORDS_JSONL)"
	test -n "$(QUALITY_EMBEDDING_JSONL)"
	test -n "$(QUALITY_QUERIES_JSON)"
	python3 tools/make_quality_fixture.py --records-jsonl "$(QUALITY_RECORDS_JSONL)" --embedding-jsonl "$(QUALITY_EMBEDDING_JSONL)" --queries-json "$(QUALITY_QUERIES_JSON)" $(QUALITY_FIXTURE_NAME_ARG) --output "$(QUALITY_FIXTURE_OUTPUT)"

report-quality-fixture:
	python3 tools/report_quality_fixture.py $(QUALITY_FIXTURE_ARG) --min-docs "$(QUALITY_FIXTURE_MIN_DOCS)" --min-queries "$(QUALITY_FIXTURE_MIN_QUERIES)" $(QUALITY_FIXTURE_REPORT_PROVENANCE_ARGS) $(QUALITY_FIXTURE_REPORT_OUTPUTS)

doctor-quality-baseline:
	test -n "$(QUALITY_BASELINE_FIXTURE_REPORT_JSON)"
	test -n "$(QUALITY_BASELINE_QUALITY_JSON)"
	python3 tools/doctor_quality_baseline.py --fixture-report-json "$(QUALITY_BASELINE_FIXTURE_REPORT_JSON)" --quality-json "$(QUALITY_BASELINE_QUALITY_JSON)" --min-docs "$(QUALITY_BASELINE_MIN_DOCS)" --min-queries "$(QUALITY_BASELINE_MIN_QUERIES)" --min-expected-labels "$(QUALITY_BASELINE_MIN_EXPECTED_LABELS)" --min-hit-rate "$(QUALITY_BASELINE_MIN_HIT_RATE)" --min-mrr "$(QUALITY_BASELINE_MIN_MRR)" $(QUALITY_BASELINE_REAL_CORPUS_ARG) $(QUALITY_BASELINE_DOCTOR_OUTPUTS)

stage-quality-provenance:
	if test -n "$(QUALITY_PROVENANCE_JSON)"; then \
		test -n "$(QUALITY_RUN_PROVENANCE_JSON)"; \
		test -f "$(QUALITY_PROVENANCE_JSON)"; \
		mkdir -p "$$(dirname "$(QUALITY_RUN_PROVENANCE_JSON)")"; \
		if test -e "$(QUALITY_RUN_PROVENANCE_JSON)" && test "$(QUALITY_PROVENANCE_JSON)" -ef "$(QUALITY_RUN_PROVENANCE_JSON)"; then \
			:; \
		else \
			cp "$(QUALITY_PROVENANCE_JSON)" "$(QUALITY_RUN_PROVENANCE_JSON)"; \
		fi; \
	fi

quality-finalization-preflight:
	if test -z "$(QUALITY_INPUT_PREFLIGHT_GATE)"; then \
		:; \
	else \
		$(MAKE) preflight-quality-inputs \
			QUALITY_INPUT_PREFLIGHT_CORPUS="$(QUALITY_INPUT_PREFLIGHT_CORPUS)" \
			QUALITY_INPUT_PREFLIGHT_QUERIES_JSON="$(QUALITY_INPUT_PREFLIGHT_QUERIES_JSON)" \
			QUALITY_INPUT_PREFLIGHT_QRELS_JSON="$(QUALITY_INPUT_PREFLIGHT_QRELS_JSON)" \
			QUALITY_INPUT_PREFLIGHT_RECORDS_JSONL="$(QUALITY_INPUT_PREFLIGHT_RECORDS_JSONL)" \
			QUALITY_INPUT_PREFLIGHT_PROVENANCE_JSON="$(QUALITY_INPUT_PREFLIGHT_PROVENANCE_JSON)" \
			QUALITY_INPUT_PREFLIGHT_MANIFEST_JSON="$(QUALITY_INPUT_PREFLIGHT_MANIFEST_JSON)" \
			QUALITY_INPUT_PREFLIGHT_JSON="$(QUALITY_INPUT_PREFLIGHT_JSON)" \
			QUALITY_INPUT_PREFLIGHT_MARKDOWN="$(QUALITY_INPUT_PREFLIGHT_MARKDOWN)"; \
	fi

finalize-quality-run:
	test -n "$(RUN_DIR)"
	mkdir -p "$(RUN_DIR)"
	$(MAKE) quality-finalization-preflight
	$(MAKE) stage-quality-provenance QUALITY_PROVENANCE_JSON="$(QUALITY_PROVENANCE_JSON)" QUALITY_RUN_PROVENANCE_JSON="$(QUALITY_RUN_PROVENANCE_JSON)"
	$(MAKE) report-quality-fixture QUALITY_FIXTURE="$(QUALITY_FIXTURE)" QUALITY_PROVENANCE_JSON="$(QUALITY_REPORT_PROVENANCE_JSON)" QUALITY_MIN_SOURCE_DOCS="$(QUALITY_MIN_SOURCE_DOCS)" QUALITY_MAX_SOURCE_SKIPPED_RATIO="$(QUALITY_MAX_SOURCE_SKIPPED_RATIO)" QUALITY_FIXTURE_MIN_DOCS="$(QUALITY_FIXTURE_MIN_DOCS)" QUALITY_FIXTURE_MIN_QUERIES="$(QUALITY_FIXTURE_MIN_QUERIES)" QUALITY_FIXTURE_REPORT_JSON="$(QUALITY_RUN_FIXTURE_REPORT_JSON)" QUALITY_FIXTURE_REPORT_MARKDOWN="$(QUALITY_RUN_FIXTURE_REPORT_MARKDOWN)"
	$(MAKE) eval-quality QUALITY_FIXTURE="$(QUALITY_FIXTURE)" QUALITY_JSON="$(QUALITY_RUN_JSON)" QUALITY_MARKDOWN="$(QUALITY_RUN_MARKDOWN)" QUERY_STATEMENT_TIMEOUT_SECONDS="$(QUERY_STATEMENT_TIMEOUT_SECONDS)"
	$(MAKE) doctor-quality-baseline RUN_DIR="$(RUN_DIR)" QUALITY_BASELINE_FIXTURE_REPORT_JSON="$(QUALITY_RUN_FIXTURE_REPORT_JSON)" QUALITY_BASELINE_QUALITY_JSON="$(QUALITY_RUN_JSON)" QUALITY_BASELINE_REQUIRE_REAL_CORPUS="$(QUALITY_BASELINE_REQUIRE_REAL_CORPUS)"
	$(MAKE) finalize-run-directory RUN_DIR="$(RUN_DIR)" RUN_METADATA_COMMAND="$(QUALITY_RUN_METADATA_COMMAND)" RUN_METADATA_ENV="$(RUN_METADATA_ENV)" RUN_METADATA_JSON="$(RUN_METADATA_JSON)" RUN_METADATA_MARKDOWN="$(RUN_METADATA_MARKDOWN)" RUN_DOCTOR_PROFILE=quality RUN_DOCTOR_REQUIRE="$(strip $(QUALITY_RUN_DOCTOR_REQUIRE) $(QUALITY_RUN_PROVENANCE_REQUIRE) $(RUN_DOCTOR_REQUIRE))" RUN_DOCTOR_JSON="$(RUN_DOCTOR_JSON)" RUN_DOCTOR_MARKDOWN="$(RUN_DOCTOR_MARKDOWN)" RUN_MANIFEST_JSON="$(RUN_MANIFEST_JSON)" RUN_MANIFEST_MARKDOWN="$(RUN_MANIFEST_MARKDOWN)"

public-warc-quality-fixture:
	python3 tools/make_public_warc_quality_fixture.py --url "$(PUBLIC_WARC_URL)" $(PUBLIC_WARC_PATH_ARG) $(PUBLIC_WARC_SOURCE_SPEC_ARG) $(PUBLIC_WARC_QUERY_SPEC_ARG) $(PUBLIC_WARC_PROVENANCE_ARG) --vector-dim $(PUBLIC_WARC_VECTOR_DIM) --query-name "$(PUBLIC_WARC_QUERY_NAME)" --query "$(PUBLIC_WARC_QUERY)" --label-text "$(PUBLIC_WARC_LABEL_TEXT)" --name "$(PUBLIC_WARC_QUALITY_NAME)" --output "$(PUBLIC_WARC_QUALITY_FIXTURE)" $(PUBLIC_WARC_QUALITY_ARTIFACT_OUTPUTS)

finalize-public-warc-quality-run:
	test -n "$(RUN_DIR)"
	mkdir -p "$(RUN_DIR)"
	$(MAKE) public-warc-quality-fixture PUBLIC_WARC_QUALITY_FIXTURE="$(PUBLIC_WARC_QUALITY_RUN_FIXTURE)" PUBLIC_WARC_SOURCE_SPEC_JSON="$(PUBLIC_WARC_SOURCE_SPEC_JSON)" PUBLIC_WARC_PROVENANCE_JSON="$(PUBLIC_WARC_PROVENANCE_JSON)" PUBLIC_WARC_QUALITY_RECORDS_JSONL="$(PUBLIC_WARC_QUALITY_RECORDS_JSONL)" PUBLIC_WARC_QUALITY_EMBEDDING_JSONL="$(PUBLIC_WARC_QUALITY_EMBEDDING_JSONL)" PUBLIC_WARC_QUALITY_QUERIES_JSON="$(PUBLIC_WARC_QUALITY_QUERIES_JSON)"
	$(MAKE) finalize-quality-run RUN_DIR="$(RUN_DIR)" QUALITY_FIXTURE="$(PUBLIC_WARC_QUALITY_RUN_FIXTURE)" QUALITY_PROVENANCE_JSON="$(PUBLIC_WARC_PROVENANCE_JSON)" QUALITY_MIN_SOURCE_DOCS="$(QUALITY_MIN_SOURCE_DOCS)" QUALITY_MAX_SOURCE_SKIPPED_RATIO="$(QUALITY_MAX_SOURCE_SKIPPED_RATIO)" QUALITY_FIXTURE_MIN_DOCS="$(QUALITY_FIXTURE_MIN_DOCS)" QUALITY_FIXTURE_MIN_QUERIES="$(QUALITY_FIXTURE_MIN_QUERIES)" RUN_METADATA_COMMAND="$(PUBLIC_WARC_QUALITY_RUN_METADATA_COMMAND)" RUN_DOCTOR_REQUIRE="$(strip $(PUBLIC_WARC_QUALITY_RUN_DOCTOR_REQUIRE) $(RUN_DOCTOR_REQUIRE))" QUALITY_JSON="$(QUALITY_JSON)" QUALITY_MARKDOWN="$(QUALITY_MARKDOWN)" QUALITY_FIXTURE_REPORT_JSON="$(QUALITY_FIXTURE_REPORT_JSON)" QUALITY_FIXTURE_REPORT_MARKDOWN="$(QUALITY_FIXTURE_REPORT_MARKDOWN)" RUN_METADATA_JSON="$(RUN_METADATA_JSON)" RUN_METADATA_MARKDOWN="$(RUN_METADATA_MARKDOWN)" RUN_DOCTOR_JSON="$(RUN_DOCTOR_JSON)" RUN_DOCTOR_MARKDOWN="$(RUN_DOCTOR_MARKDOWN)" RUN_MANIFEST_JSON="$(RUN_MANIFEST_JSON)" RUN_MANIFEST_MARKDOWN="$(RUN_MANIFEST_MARKDOWN)"

doctor-real-corpus-input:
	test -n "$(REAL_CORPUS_INPUT_JSON)"
	python3 tools/doctor_real_corpus_input.py --manifest-json "$(REAL_CORPUS_INPUT_JSON)" --min-queries "$(REAL_CORPUS_INPUT_MIN_QUERIES)" --max-queries "$(REAL_CORPUS_INPUT_MAX_QUERIES)" $(REAL_CORPUS_INPUT_DOCTOR_OUTPUTS)

preflight-quality-inputs:
	test -n "$(QUALITY_INPUT_PREFLIGHT_CORPUS)"
	test -n "$(QUALITY_INPUT_PREFLIGHT_QUERIES_JSON)"
	test -n "$(QUALITY_INPUT_PREFLIGHT_QRELS_JSON)"
	python3 tools/preflight_quality_inputs.py $(QUALITY_INPUT_PREFLIGHT_CORPUS_ARGS) --queries-json "$(QUALITY_INPUT_PREFLIGHT_QUERIES_JSON)" --qrels-json "$(QUALITY_INPUT_PREFLIGHT_QRELS_JSON)" $(QUALITY_INPUT_PREFLIGHT_OPTIONAL_ARGS)
# Opt-in structural validator for one synthetic quality attempt identity
# envelope. Never invoked by verify, eval-quality, or run finalization.
doctor-quality-attempt-identity:
	test -n "$(QUALITY_ATTEMPT_IDENTITY_JSON)"
	python3 tools/doctor_quality_attempt_identity.py --input-json "$(QUALITY_ATTEMPT_IDENTITY_JSON)" $(QUALITY_ATTEMPT_IDENTITY_OUTPUTS)

eval-quality:
	python3 tools/eval_quality.py $(QUALITY_FIXTURE_ARG) $(QUALITY_QUERY_TIMEOUT_ARG) $(QUERY_STATEMENT_TIMEOUT_ARG) $(QUALITY_OUTPUTS)

eval-quality-budget:
	test -n "$(ANALYSIS_MAX_ITERATIONS)"
	test -n "$(ANALYSIS_MAX_QUERIES)"
	test -n "$(ANALYSIS_DEADLINE_SECONDS)"
	python3 tools/eval_quality.py $(QUALITY_FIXTURE_ARG) --max-iterations "$(ANALYSIS_MAX_ITERATIONS)" --max-queries "$(ANALYSIS_MAX_QUERIES)" --deadline-seconds "$(ANALYSIS_DEADLINE_SECONDS)" $(QUALITY_QUERY_TIMEOUT_ARG) $(QUERY_STATEMENT_TIMEOUT_ARG) $(ANALYSIS_BUDGET_STATUS_ARG) $(QUALITY_OUTPUTS)

eval-public-warc-quality: public-warc-quality-fixture
	QUALITY_FIXTURE="$(PUBLIC_WARC_QUALITY_FIXTURE)" $(MAKE) eval-quality

smoke-public-warc:
	python3 tools/smoke_public_warc.py

build-pg-version:
	docker build --build-arg PG_MAJOR=$(PG_MAJOR) --build-arg DEV_PERMISSIONS=$(PG_DEV_PERMISSIONS) --tag $(PG_IMAGE) .

smoke-pg-version: build-pg-version
	@set -e; \
	container="$(PG_MATRIX_CONTAINER)"; \
	docker rm -f "$$container" >/dev/null 2>&1 || true; \
	trap 'docker rm -f "$$container" >/dev/null 2>&1 || true' EXIT; \
	docker run -d --name "$$container" \
		-e POSTGRES_USER="$(PG_MATRIX_USER)" \
		-e POSTGRES_PASSWORD="$(PG_MATRIX_PASSWORD)" \
		-e POSTGRES_DB="$(PG_MATRIX_DB)" \
		$(PG_IMAGE) >/dev/null; \
	timeout 90 bash -c "until docker exec $$container pg_isready -U $(PG_MATRIX_USER) -d $(PG_MATRIX_DB) >/dev/null 2>&1; do sleep 2; done"; \
	docker exec "$$container" psql -U "$(PG_MATRIX_USER)" -d "$(PG_MATRIX_DB)" -v ON_ERROR_STOP=1 -c 'CREATE EXTENSION pgwarc_lance; SELECT hello_pgwarc_lance();'; \
	docker rm -f "$$container" >/dev/null; \
	trap - EXIT; \
	printf 'smoke passed for PostgreSQL %s\n' "$(PG_MAJOR)"

pg-version-matrix:
	@set -e; \
	for version in $(PG_MATRIX); do \
		$(MAKE) PG_MAJOR=$$version smoke-pg-version; \
	done

check-release-artifacts:
	python3 tools/check_release_artifacts.py --dist-dir "$(DIST_DIR)" --version "$(EXT_VERSION)" --pg-major "$(PG_MAJOR)"

smoke-release-artifacts: check-release-artifacts
	python3 tools/smoke_release_artifacts.py --dist-dir "$(DIST_DIR)" --version "$(EXT_VERSION)" --pg-major "$(PG_MAJOR)" --postgres-image "$(ARTIFACT_SMOKE_IMAGE)" --container-name "$(ARTIFACT_SMOKE_CONTAINER)" --user "$(PG_MATRIX_USER)" --password "$(PG_MATRIX_PASSWORD)" --database "$(PG_MATRIX_DB)" --startup-timeout "$(ARTIFACT_SMOKE_TIMEOUT)"

smoke-release-upgrade:
	test -n "$(UPGRADE_OLD_VERSION)"
	test -n "$(UPGRADE_OLD_DIST_DIR)"
	python3 tools/smoke_release_upgrade.py --old-dist-dir "$(UPGRADE_OLD_DIST_DIR)" --old-version "$(UPGRADE_OLD_VERSION)" --new-dist-dir "$(UPGRADE_NEW_DIST_DIR)" --new-version "$(UPGRADE_NEW_VERSION)" --pg-major "$(PG_MAJOR)" --postgres-image "$(ARTIFACT_SMOKE_IMAGE)" --container-name "$(ARTIFACT_UPGRADE_CONTAINER)" --user "$(PG_MATRIX_USER)" --password "$(PG_MATRIX_PASSWORD)" --database "$(PG_MATRIX_DB)" --startup-timeout "$(ARTIFACT_SMOKE_TIMEOUT)"

doctor-release-upgrade-inputs:
	python3 tools/doctor_release_upgrade_inputs.py --pg-major "$(PG_MAJOR)" --new-version "$(EXT_VERSION)" $(UPGRADE_INPUT_OLD_VERSION_ARG) $(UPGRADE_INPUT_OLD_DIST_DIR_ARG) $(UPGRADE_INPUT_NEW_DIST_DIR_ARG) $(UPGRADE_INPUT_DOCTOR_OUTPUTS)

release-artifacts-matrix:
	@set -e; \
	for version in $(PG_MATRIX); do \
		$(MAKE) PG_MAJOR=$$version release-artifacts; \
	done

smoke-release-artifacts-matrix:
	@set -e; \
	for version in $(PG_MATRIX); do \
		$(MAKE) PG_MAJOR=$$version smoke-release-artifacts; \
	done

smoke-release-upgrade-matrix:
	test -n "$(UPGRADE_OLD_VERSION)"
	@set -e; \
	for version in $(PG_MATRIX); do \
		$(MAKE) PG_MAJOR=$$version smoke-release-upgrade; \
	done

report-release-artifacts:
	python3 tools/report_release_artifacts.py --pg-majors "$(PG_MATRIX)" --version "$(EXT_VERSION)" $(RELEASE_MATRIX_OUTPUTS)

report-release-smoke-matrix:
	@if [ "$(RELEASE_SMOKE_TARGET)" = "smoke-release-upgrade" ]; then \
		$(MAKE) report-release-upgrade-smoke-matrix RELEASE_SMOKE_JSON="$(RELEASE_SMOKE_JSON)" RELEASE_SMOKE_MARKDOWN="$(RELEASE_SMOKE_MARKDOWN)"; \
	else \
		python3 tools/report_release_smoke_matrix.py --pg-majors "$(PG_MATRIX)" --make-program "$(RELEASE_SMOKE_MAKE_PROGRAM)" --make-target "$(RELEASE_SMOKE_TARGET)" --output-tail-lines "$(RELEASE_SMOKE_OUTPUT_LINES)" $(RELEASE_SMOKE_MAKE_VAR_ARGS) $(RELEASE_SMOKE_OUTPUTS); \
	fi

report-release-upgrade-smoke-matrix:
	python3 tools/report_release_upgrade_smoke_matrix.py --pg-majors "$(PG_MATRIX)" --make-program "$(RELEASE_SMOKE_MAKE_PROGRAM)" --make-target "$(RELEASE_SMOKE_TARGET)" --dist-root "$(CURDIR)/dist" --new-version "$(EXT_VERSION)" --output-tail-lines "$(RELEASE_SMOKE_OUTPUT_LINES)" $(RELEASE_SMOKE_MAKE_VAR_ARGS) $(RELEASE_SMOKE_OUTPUTS)

finalize-release-run:
	test -n "$(RUN_DIR)"
	mkdir -p "$(RUN_DIR)"
	$(MAKE) report-release-artifacts RELEASE_MATRIX_JSON="$(RELEASE_RUN_ARTIFACTS_JSON)" RELEASE_MATRIX_MARKDOWN="$(RELEASE_RUN_ARTIFACTS_MARKDOWN)"
	$(MAKE) report-release-smoke-matrix RELEASE_SMOKE_JSON="$(RELEASE_RUN_SMOKE_JSON)" RELEASE_SMOKE_MARKDOWN="$(RELEASE_RUN_SMOKE_MARKDOWN)"
	$(MAKE) finalize-run-directory RUN_DIR="$(RUN_DIR)" RUN_METADATA_COMMAND="$(RELEASE_RUN_METADATA_COMMAND)" RUN_METADATA_ENV="$(RUN_METADATA_ENV)" RUN_METADATA_JSON="$(RUN_METADATA_JSON)" RUN_METADATA_MARKDOWN="$(RUN_METADATA_MARKDOWN)" RUN_DOCTOR_PROFILE=packaging RUN_DOCTOR_REQUIRE="$(RUN_DOCTOR_REQUIRE)" RUN_DOCTOR_JSON="$(RUN_DOCTOR_JSON)" RUN_DOCTOR_MARKDOWN="$(RUN_DOCTOR_MARKDOWN)" RUN_MANIFEST_JSON="$(RUN_MANIFEST_JSON)" RUN_MANIFEST_MARKDOWN="$(RUN_MANIFEST_MARKDOWN)"

doctor-import-summary:
	test -n "$(IMPORT_SUMMARY)"
	python3 tools/doctor_import_summary.py --summary-json "$(IMPORT_SUMMARY)" $(IMPORT_DOCTOR_OUTPUTS)

finalize-import-run:
	test -n "$(RUN_DIR)"
	test -n "$(IMPORT_SUMMARY)"
	mkdir -p "$(RUN_DIR)"
	if [ "$(IMPORT_SUMMARY)" != "$(IMPORT_RUN_SUMMARY)" ]; then cp "$(IMPORT_SUMMARY)" "$(IMPORT_RUN_SUMMARY)"; fi
	$(MAKE) doctor-import-summary IMPORT_SUMMARY="$(IMPORT_RUN_SUMMARY)" IMPORT_DOCTOR_JSON="$(IMPORT_RUN_DOCTOR_JSON)" IMPORT_DOCTOR_MARKDOWN="$(IMPORT_RUN_DOCTOR_MARKDOWN)"
	$(MAKE) finalize-run-directory RUN_DIR="$(RUN_DIR)" RUN_METADATA_COMMAND="$(IMPORT_RUN_METADATA_COMMAND)" RUN_METADATA_ENV="$(RUN_METADATA_ENV)" RUN_METADATA_JSON="$(RUN_METADATA_JSON)" RUN_METADATA_MARKDOWN="$(RUN_METADATA_MARKDOWN)" RUN_DOCTOR_PROFILE=import RUN_DOCTOR_REQUIRE="$(strip $(IMPORT_RUN_DOCTOR_REQUIRE) $(RUN_DOCTOR_REQUIRE))" RUN_DOCTOR_JSON="$(RUN_DOCTOR_JSON)" RUN_DOCTOR_MARKDOWN="$(RUN_DOCTOR_MARKDOWN)" RUN_MANIFEST_JSON="$(RUN_MANIFEST_JSON)" RUN_MANIFEST_MARKDOWN="$(RUN_MANIFEST_MARKDOWN)"

report-run-directory:
	test -n "$(RUN_DIR)"
	test -d "$(RUN_DIR)"
	python3 tools/report_run_directory.py --run-dir "$(RUN_DIR)" $(RUN_MANIFEST_OUTPUTS)

write-run-metadata:
	test -n "$(RUN_DIR)"
	mkdir -p "$(RUN_DIR)"
	python3 tools/write_run_metadata.py --run-dir "$(RUN_DIR)" $(RUN_METADATA_COMMAND_ARG) $(RUN_METADATA_ENV_ARGS) $(RUN_METADATA_OUTPUTS)

doctor-run-directory:
	test -n "$(RUN_DIR)"
	test -d "$(RUN_DIR)"
	python3 tools/doctor_run_directory.py --run-dir "$(RUN_DIR)" --profile "$(RUN_DOCTOR_PROFILE)" $(RUN_DOCTOR_REQUIRE_ARGS) $(RUN_DOCTOR_OUTPUTS)

finalize-run-directory:
	test -n "$(RUN_DIR)"
	mkdir -p "$(RUN_DIR)"
	$(MAKE) write-run-metadata RUN_DIR="$(RUN_DIR)" RUN_METADATA_COMMAND="$(RUN_METADATA_COMMAND)" RUN_METADATA_ENV="$(RUN_METADATA_ENV)" RUN_METADATA_JSON="$(RUN_METADATA_JSON)" RUN_METADATA_MARKDOWN="$(RUN_METADATA_MARKDOWN)"
	$(MAKE) report-run-directory RUN_DIR="$(RUN_DIR)" RUN_MANIFEST_JSON="$(RUN_MANIFEST_JSON)" RUN_MANIFEST_MARKDOWN="$(RUN_MANIFEST_MARKDOWN)"
	$(MAKE) doctor-run-directory RUN_DIR="$(RUN_DIR)" RUN_DOCTOR_PROFILE="$(RUN_DOCTOR_PROFILE)" RUN_DOCTOR_REQUIRE="$(RUN_DOCTOR_REQUIRE)" RUN_DOCTOR_JSON="$(RUN_DOCTOR_JSON)" RUN_DOCTOR_MARKDOWN="$(RUN_DOCTOR_MARKDOWN)"
	$(MAKE) report-run-directory RUN_DIR="$(RUN_DIR)" RUN_MANIFEST_JSON="$(RUN_MANIFEST_JSON)" RUN_MANIFEST_MARKDOWN="$(RUN_MANIFEST_MARKDOWN)"

release-artifacts: build-pg-version
	mkdir -p $(DIST_DIR)
	docker rm -f $(ARTIFACT_CONTAINER) >/dev/null 2>&1 || true
	docker create --name $(ARTIFACT_CONTAINER) $(PG_IMAGE) >/dev/null
	docker cp $(ARTIFACT_CONTAINER):/usr/lib/postgresql/$(PG_MAJOR)/lib/pgwarc_lance.so $(DIST_DIR)/
	docker cp $(ARTIFACT_CONTAINER):/usr/share/postgresql/$(PG_MAJOR)/extension/pgwarc_lance.control $(DIST_DIR)/
	docker cp $(ARTIFACT_CONTAINER):/usr/share/postgresql/$(PG_MAJOR)/extension/pgwarc_lance--$(EXT_VERSION).sql $(DIST_DIR)/
	docker rm $(ARTIFACT_CONTAINER) >/dev/null
	cp LICENSE NOTICE $(DIST_DIR)/
	cp sql/pgwarc_lance--*--*.sql sql/pgwarc_lance-restrict-access.sql $(DIST_DIR)/
	$(MAKE) check-release-artifacts
	@printf 'wrote %s\n' "$(DIST_DIR)"

clean:
	docker compose down -v

.PHONY: test-uri-policy
# Pure filesystem containment tests; no PostgreSQL or running database required.
test-uri-policy:
	@set -eu; output=$$(mktemp /tmp/pgwarc-uri-policy.XXXXXX); trap 'rm -f "$$output"' EXIT; rustc --edition=2021 --test src/uri_policy.rs -o "$$output"; "$$output"

.PHONY: test-runtime-safety
test-runtime-safety:
	python3 tests/db_runtime_safety.py

.PHONY: test-backup-restore
test-backup-restore:
	python3 tests/db_backup_restore.py --pg-bin /usr/lib/postgresql/$(PG_MAJOR)/bin

.PHONY: test-ingest-replay
test-ingest-replay:
	python3 tests/db_ingest_replay.py --pg-bin /usr/lib/postgresql/$(PG_MAJOR)/bin

.PHONY: test-write-cancellation
test-write-cancellation:
	python3 tests/db_write_cancellation.py

.PHONY: audit-dependencies
# Requires cargo-audit 0.22.2; fetch the current advisory database on every run.
# Maintenance warnings remain visible; known vulnerabilities, unsoundness and yanks fail.
audit-dependencies:
	cargo audit --deny unsound --deny yanked --target-arch x86_64 --target-os linux

.PHONY: test-storage-faults
# Requires extracted PG16 release artifacts. Creates and removes its own container.
test-storage-faults:
	python3 tests/db_storage_faults.py --dist-dir "$(DIST_DIR)" --version "$(EXT_VERSION)" --postgres-image "$(ARTIFACT_SMOKE_IMAGE)"

.PHONY: test-search-memory
test-search-memory:
	python3 tests/db_search_memory.py

.PHONY: test-bm25-snapshot
test-bm25-snapshot:
	python3 tests/db_bm25_snapshot.py

.PHONY: test-storage-corruption
# Damages only generated copies and restores SQL/Lance/roles into a fresh cluster.
test-storage-corruption:
	python3 tests/db_storage_corruption.py --dist-dir "$(DIST_DIR)" --version "$(EXT_VERSION)" --postgres-image "$(ARTIFACT_SMOKE_IMAGE)"
